<a href="https://colab.research.google.com/github/keerthana2819/Practice/blob/main/DE%20Course%20Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Print the array
print(array)

[1 2 3 4 5]


In [2]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = array.reshape(2, 3)

# Print the reshaped array
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# Create a NumPy array with values from 10 to 19
array = np.arange(10, 20)

# Print the array
print(array)

[10 11 12 13 14 15 16 17 18 19]


In [4]:
import numpy as np

# Create a 7x7 matrix of zeros
zero_matrix = np.zeros((7, 7))

# Print the zero matrix
print(zero_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Calculate the mean of the array
mean_value = np.mean(array)

# Print the mean value
print("Mean of the array:", mean_value)

Mean of the array: 3.0
