<a href="https://colab.research.google.com/github/keerthana2819/Practice/blob/main/Numpy_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Create two random matrices
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

# Perform matrix operations
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nMatrix Addition:\n", matrix1 + matrix2)
print("\nMatrix Multiplication:\n", np.dot(matrix1, matrix2))
print("\nTranspose of Matrix 1:\n", matrix1.T)

Matrix 1:
 [[9 1 4]
 [8 5 2]
 [5 6 4]]

Matrix 2:
 [[5 3 8]
 [5 3 6]
 [9 2 3]]

Matrix Addition:
 [[14  4 12]
 [13  8  8]
 [14  8  7]]

Matrix Multiplication:
 [[ 86  38  90]
 [ 83  43 100]
 [ 91  41  88]]

Transpose of Matrix 1:
 [[9 8 5]
 [1 5 6]
 [4 2 4]]
